version: "3"

tasks:
  build:
    desc: Build content-processor CLI
    cmds:
      - go build -o bin/content-processor .
    sources:
      - "*.go"
      - go.mod
    generates:
      - bin/content-processor
    method: checksum

  run:
    desc: Run without building
    cmds:
      - go run . {{.CLI_ARGS}}

  clean:
    desc: Remove built binaries
    cmds:
      - rm -rf bin/

  test:
    desc: Test CLI help
    cmds:
      - go run .
